/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SystemSettingsPanel.java
 *
 * Created on May 6, 2010, 7:40:42 PM
 */

package cis406;

import java.io.*;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;

/**
 *
 * @author qwerty
 */
public class AdministratorPanel extends javax.swing.JPanel implements CisPanel{

    /** Creates new form SystemSettingsPanel */
    public AdministratorPanel() {
        initComponents();
    }

    public void clickNew() {

    }

    public void clickSave() {
        Configuration config = new Configuration(Integer.parseInt(txtTimeout.getText()),
                Integer.parseInt(txtPasswordInterval.getText()), Integer.parseInt(txtPasswordLength.getText()));

        Writer output = null;
        File file = new File("internapp.config");
        try {
                output = new BufferedWriter(new FileWriter(file));
                output.write(config.getPassword_interval() + "|"
                                + config.getPassword_length() + "|"
                                + config.getSession_timeout());
                output.close();
                System.out.println("Your file has been written");
        } catch (Exception e) {

        }
    }

    public void clickLoad() {

    }

    public void clickDelete() {

    }

    public void clickClear() {

    }

    public void clickReport() {

    }

    public void clickForm() {

    }

    public void switchTo(javax.swing.ButtonGroup activeView) {

    }

    public void switchAway() {

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTimeout = new javax.swing.JTextField();
        txtPasswordInterval = new javax.swing.JTextField();
        txtPasswordLength = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        btnReadUserLog = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUserLogs = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLogDescription = new javax.swing.JTextArea();
        txtLogID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cis406.MainApp.class).getContext().getResourceMap(AdministratorPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txtTimeout.setText(resourceMap.getString("txtTimeout.text")); // NOI18N
        txtTimeout.setName("txtTimeout"); // NOI18N

        txtPasswordInterval.setText(resourceMap.getString("txtPasswordInterval.text")); // NOI18N
        txtPasswordInterval.setName("txtPasswordInterval"); // NOI18N

        txtPasswordLength.setText(resourceMap.getString("txtPasswordLength.text")); // NOI18N
        txtPasswordLength.setName("txtPasswordLength"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstUsers.setName("lstUsers"); // NOI18N
        lstUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsersValueChanged(evt);
            }
        });
        lstUsers.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lstUsersComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(lstUsers);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        btnReadUserLog.setText(resourceMap.getString("btnReadUserLog.text")); // NOI18N
        btnReadUserLog.setName("btnReadUserLog"); // NOI18N
        btnReadUserLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadUserLogActionPerformed(evt);
            }
        });

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        lstUserLogs.setName("lstUserLogs"); // NOI18N
        lstUserLogs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUserLogsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstUserLogs);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtLogDescription.setColumns(20);
        txtLogDescription.setEditable(false);
        txtLogDescription.setRows(5);
        txtLogDescription.setName("txtLogDescription"); // NOI18N
        jScrollPane2.setViewportView(txtLogDescription);

        txtLogID.setEditable(false);
        txtLogID.setName("txtLogID"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        txtUserID.setEditable(false);
        txtUserID.setName("txtUserID"); // NOI18N

        txtDate.setEditable(false);
        txtDate.setName("txtDate"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtPasswordLength))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPasswordInterval)
                                .addComponent(txtTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(btnReadUserLog)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUserID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                        .addComponent(txtLogID, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReadUserLog)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLogID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPasswordInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswordLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsersValueChanged
        DefaultListModel model = new DefaultListModel();
        try {
            ResultSet rs = Database.execute("select user_log_id from user_log where user_id = '" + lstUsers.getSelectedValue() + "'");
            while (rs.next()) {
                int pos = model.getSize();
                model.add(pos, rs.getString("user_log_id"));
            }

        } catch (Exception e) {
            System.out.println("Could not execute query");
            System.out.println(e.getMessage());
        }

        lstUserLogs.setModel(model);
}//GEN-LAST:event_lstUsersValueChanged

    private void lstUsersComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lstUsersComponentAdded

}//GEN-LAST:event_lstUsersComponentAdded

    private void btnReadUserLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadUserLogActionPerformed

        DefaultListModel model = new DefaultListModel();
        try {
            ResultSet rs = Database.execute("select distinct user_id from user_log");
            while (rs.next()) {
                int pos = model.getSize();
                model.add(pos, rs.getString("user_id"));
            }

        } catch (Exception e) {
            System.out.println("Could not execute query");
            System.out.println(e.getMessage());
        }

        lstUsers.setModel(model);
}//GEN-LAST:event_btnReadUserLogActionPerformed

    private void lstUserLogsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUserLogsValueChanged
        SecurityLog log = new SecurityLog();
        String[] logInfo = log.getUserLog(lstUserLogs.getSelectedValue().toString());
        txtLogID.setText(logInfo[0]);
        txtUserID.setText(logInfo[3]);
        txtDate.setText(logInfo[1]);
        txtLogDescription.setText(logInfo[2]);
}//GEN-LAST:event_lstUserLogsValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReadUserLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstUserLogs;
    private javax.swing.JList lstUsers;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtLogDescription;
    private javax.swing.JTextField txtLogID;
    private javax.swing.JTextField txtPasswordInterval;
    private javax.swing.JTextField txtPasswordLength;
    private javax.swing.JTextField txtTimeout;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables

}
