package cis406;

/**
 *
 * @author Mark Lenser
 */
public class ContactBrowsePanel extends javax.swing.JPanel implements CisPanel {
    

    /** Creates new form AddContact */
    public ContactBrowsePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(681, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void clickNew() {
    }
    public void clickSave() {
    }
    public void clickLoad() {
    }
    public void clickDelete() {
    }
    public void clickClear() {
    }
    public void clickCancel() {
    }
    public void clickEditing() {
    }
    public void clickBrowsing() {
    }
    public void switchTo(String actionCommand) {
    }
    public void switchAway() {
    }
}