/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InternshipReportPanel.java
 *
 * Created on May 10, 2010, 2:47:41 PM
 */

package cis406;

import javax.swing.ButtonGroup;

/**
 *
 * @author Dean
 */
public class InternshipReportPanel extends javax.swing.JPanel implements CisPanel {

    /** Creates new form InternshipReportPanel */
    public InternshipReportPanel() {
        initComponents();

        reportTable.setModel(Internship.generateTable());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Sr Web Developr", "02-06-2010", "NASA", "Web Development", new Integer(2)},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Posted", "Company", "Career Path", "Positions Open"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        reportTable.setColumnSelectionAllowed(true);
        reportTable.setName("reportTable"); // NOI18N
        jScrollPane1.setViewportView(reportTable);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cis406.MainApp.class).getContext().getResourceMap(InternshipReportPanel.class);
        reportTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reportTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("reportTable.columnModel.title0")); // NOI18N
        reportTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("reportTable.columnModel.title1")); // NOI18N
        reportTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("reportTable.columnModel.title2")); // NOI18N
        reportTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("reportTable.columnModel.title3")); // NOI18N
        reportTable.getColumnModel().getColumn(4).setResizable(false);
        reportTable.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("reportTable.columnModel.title4")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void clickClear() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void clickDelete() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void clickForm() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void clickLoad() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void clickNew() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void clickReport() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void clickSave() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void switchAway() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void switchTo(ButtonGroup activeView) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reportTable;
    // End of variables declaration//GEN-END:variables



}
