/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SystemSettingsPanel.java
 *
 * Created on May 6, 2010, 7:40:42 PM
 */

package cis406;

import java.awt.CardLayout;

/**
 *
 * @author qwerty
 */
public class SecurityLogPanel extends javax.swing.JPanel implements CisPanel{

    /** Creates new form SystemSettingsPanel */
    public SecurityLogPanel() {
        initComponents();
        /*
        DefaultListModel model = new DefaultListModel();
        try {
            ResultSet rs = Database.execute("select distinct users_id from user_log");
            while (rs.next()) {
                int pos = model.getSize();
                model.add(pos, rs.getString("users_id"));
            }

        } catch (Exception e) {
            System.out.println("Could not execute query");
            System.out.println(e.getMessage());
        }
          */
      //  lstUsers.setModel(model);
    }

    static public CisTable generateTable() {
        CisTable table = new CisTable("user_log");
        table.addDisplayField("users_id");
        table.addDisplayField("date");
        table.addDisplayField("time");
        table.addDisplayField("description");
        return table.parseData();
    }

    public void clickNew() {

    }

    public void clickSave() {

    }

    public void clickLoad() {
    }

    public void clickDelete() {

    }

    public void clickClear() {

    }

    public void clickCancel() {
        
    }

    public void clickBrowsing() {
        CardLayout cl = (CardLayout) (getLayout());
        cl.show(this, "Report");
        //activeCard = "Report";
    }

    public void clickEditing() {

    }

    public void switchTo(String actionCommand) {

    }

    public void switchAway() {

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(generateTable());
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
