/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BrowsePanel.java
 *
 * Created on May 10, 2010, 2:47:41 PM
 */

package cis406.internship;

import cis406.CisPanel;

/**
 *
 * @author Dean
 */
public class BrowsePanel extends javax.swing.JPanel implements CisPanel {

    /** Creates new form BrowsePanel */
    public BrowsePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        reportTable.setColumnSelectionAllowed(true);
        reportTable.setName("reportTable"); // NOI18N
        jScrollPane1.setViewportView(reportTable);
        reportTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void clickClear() {
    }
    
    public void clickCancel() {
    }

    public void clickDelete() {
    }

    public void clickEditing() {
    }

    public void clickLoad() {
    }

    public void clickNew() {
    }

    public void clickBrowsing() {
    }

    public void clickSave() {
    }

    public void switchAway() {
    }

    public void switchTo(String actionCommand) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reportTable;
    // End of variables declaration//GEN-END:variables



}
