/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportDialog.java
 *
 * Created on May 30, 2010, 3:52:54 PM
 */
package cis406.internship;

import cis406.Database;
import cis406.Printer;
import java.sql.ResultSet;
import org.jdesktop.application.Action;

/**
 *
 * @author Dean
 */
public class ReportDialog extends javax.swing.JDialog {

    /** Creates new form ReportDialog */
    public ReportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endDateLabel = new javax.swing.JLabel();
        endDateField = new javax.swing.JFormattedTextField();
        startDateLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        startDateField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cis406.MainApp.class).getContext().getResourceMap(ReportDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        endDateLabel.setText(resourceMap.getString("endDateLabel.text")); // NOI18N
        endDateLabel.setName("endDateLabel"); // NOI18N

        try {
            endDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        endDateField.setText(resourceMap.getString("endDateField.text")); // NOI18N
        endDateField.setToolTipText(resourceMap.getString("endDateField.toolTipText")); // NOI18N
        endDateField.setName("endDateField"); // NOI18N

        startDateLabel.setText(resourceMap.getString("startDateLabel.text")); // NOI18N
        startDateLabel.setName("startDateLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cis406.MainApp.class).getContext().getActionMap(ReportDialog.class, this);
        printButton.setAction(actionMap.get("print")); // NOI18N
        printButton.setText(resourceMap.getString("printButton.text")); // NOI18N
        printButton.setName("printButton"); // NOI18N

        try {
            startDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        startDateField.setText(resourceMap.getString("startDateField.text")); // NOI18N
        startDateField.setToolTipText(resourceMap.getString("startDateField.toolTipText")); // NOI18N
        startDateField.setName("startDateField"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(printButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(endDateLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                            .add(layout.createSequentialGroup()
                                .add(startDateLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(startDateField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .add(endDateField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(startDateLabel)
                    .add(startDateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(endDateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(endDateLabel))
                .add(18, 18, 18)
                .add(printButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void load() {
        ReportDialog dialog = new ReportDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }

    @Action
    public void print() {
        ResultSet rows;
        String query = "SELECT COUNT(*) AS internships FROM internship WHERE post_date < '" + endDateField.getText() + "' AND post_date > '" + startDateField.getText() + "' AND ";
        query = "SELECT COUNT(*) AS internships FROM internship WHERE ";
        String report = "Internship Summary Report \n\nFrom: " + startDateField.getText() + " To: " + endDateField.getText();
        try {
            ResultSet category = Database.read("career_path");
            report += "Internships by Career Path\n=======================\n";
            while (category.next()) {
                rows = Database.execute(query + "career_path_id = " + category.getString("career_path_id"));
                while (rows.next()) {
                report += "\n" + category.getString("name") + ": " + rows.getString("internships");
                }
            }
            report += "\n\nInternships by Industry\n=======================\n";
            category = Database.read("industry");
            while (category.next()) {
                rows = Database.execute(query + "career_path_id = " + category.getString("industry_id"));
                while (rows.next()) {
                report += "\n" + category.getString("industry_name") + ": " + rows.getString("internships");
                }
            }

            System.out.println(report);
            Printer pr = new Printer();
            pr.print(report);

        } catch (Exception e) {
            System.out.println("Failed to add the fields from the data");
            System.out.println(e.getMessage());
        }
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField endDateField;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JFormattedTextField startDateField;
    private javax.swing.JLabel startDateLabel;
    // End of variables declaration//GEN-END:variables
}
