/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TaskReportPanel.java
 *
 * Created on May 18, 2010, 10:57:17 AM
 */
package cis406.student;

import cis406.TableModel;
import cis406.internship.Internship;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class TaskBrowsePanel extends javax.swing.JPanel {

    /** Creates new form TaskReportPanel */
    public TaskBrowsePanel() {
        initComponents();
        loadTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reportTable.setName("reportTable"); // NOI18N
        jScrollPane1.setViewportView(reportTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reportTable;
    // End of variables declaration//GEN-END:variables

    public void loadTable() {
        reportTable.setModel(Task.generateTable());
    }

    public void delete() {
        int rowId = getSelectedRow();
        if (Internship.delete(rowId)) {
            JOptionPane.showMessageDialog(null, "Task #" + rowId + " was deleted");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(null, "Task #" + rowId + " could not be found");
        }
    }

    public int getSelectedRow() {
        int row = reportTable.getSelectedRow();
        if (row != -1) {
            return ((TableModel) reportTable.getModel()).getRowId(row);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row first");
            return 0;
        }
    }
}
