package cis406.contact;

import cis406.ComboBoxModel;
import cis406.ComboItem;
import cis406.Database;
import cis406.contact.Contact;
import java.sql.ResultSet;
import java.awt.CardLayout;
/**
 *
 * @author Mark Lenser
 */
public class ContactEditPanel extends javax.swing.JPanel {
    

    /** Creates new form AddContact */
    public ContactEditPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompanyTitle = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        cboCompany = new javax.swing.JComboBox();
        lblIndustryDivision = new javax.swing.JLabel();
        cboIndustry = new javax.swing.JComboBox();
        jSeparator = new javax.swing.JSeparator();
        lblContactTitle = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        cboState = new javax.swing.JComboBox();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhoneLeftParenthesis = new javax.swing.JLabel();
        txtPhoneArea = new javax.swing.JTextField();
        lblPhoneRightParenthesis = new javax.swing.JLabel();
        txtPhoneFirst = new javax.swing.JTextField();
        txtPhoneDash = new javax.swing.JLabel();
        txtPhoneLast = new javax.swing.JTextField();
        lblPhoneExt = new javax.swing.JLabel();
        txtPhoneExt = new javax.swing.JTextField();
        lblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblCommMethod = new javax.swing.JLabel();
        cboCommMethod = new javax.swing.JComboBox();
        lblNotes = new javax.swing.JLabel();
        scpNotes = new javax.swing.JScrollPane();
        txaNotes = new javax.swing.JTextArea();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(681, 400));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cis406.MainApp.class).getContext().getResourceMap(ContactEditPanel.class);
        lblCompanyTitle.setFont(resourceMap.getFont("lblCompanyTitle.font")); // NOI18N
        lblCompanyTitle.setText(resourceMap.getString("lblCompanyTitle.text")); // NOI18N
        lblCompanyTitle.setName("lblCompanyTitle"); // NOI18N

        lblCompany.setText(resourceMap.getString("lblCompany.text")); // NOI18N
        lblCompany.setName("lblCompany"); // NOI18N

        cboCompany.setEditable(true);
        cboCompany.setModel(new cis406.ComboBoxModel("company", "name"));
        cboCompany.setName("cboCompany"); // NOI18N
        cboCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCompanyActionPerformed(evt);
            }
        });

        lblIndustryDivision.setText(resourceMap.getString("lblIndustryDivision.text")); // NOI18N
        lblIndustryDivision.setName("lblIndustryDivision"); // NOI18N

        cboIndustry.setEditable(true);
        cboIndustry.setModel(new cis406.ComboBoxModel("industry", "industry_name"));
        cboIndustry.setName("cboIndustry"); // NOI18N

        jSeparator.setName("jSeparator"); // NOI18N

        lblContactTitle.setFont(resourceMap.getFont("lblContactTitle.font")); // NOI18N
        lblContactTitle.setText(resourceMap.getString("lblContactTitle.text")); // NOI18N
        lblContactTitle.setName("lblContactTitle"); // NOI18N

        lblFName.setText(resourceMap.getString("lblFName.text")); // NOI18N
        lblFName.setName("lblFName"); // NOI18N

        txtFName.setName("txtFName"); // NOI18N

        lblLName.setText(resourceMap.getString("lblLName.text")); // NOI18N
        lblLName.setName("lblLName"); // NOI18N

        txtLName.setName("txtLName"); // NOI18N

        lblStreet.setText(resourceMap.getString("lblStreet.text")); // NOI18N
        lblStreet.setName("lblStreet"); // NOI18N

        txtStreet.setName("txtStreet"); // NOI18N

        lblZip.setText(resourceMap.getString("lblZip.text")); // NOI18N
        lblZip.setName("lblZip"); // NOI18N

        txtZip.setName("txtZip"); // NOI18N
        txtZip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtZipMouseExited(evt);
            }
        });
        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });
        txtZip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtZipFocusLost(evt);
            }
        });

        lblCity.setText(resourceMap.getString("lblCity.text")); // NOI18N
        lblCity.setName("lblCity"); // NOI18N

        txtCity.setName("txtCity"); // NOI18N

        lblState.setText(resourceMap.getString("lblState.text")); // NOI18N
        lblState.setName("lblState"); // NOI18N

        cboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" }));
        cboState.setName("cboState"); // NOI18N

        lblEmail.setText(resourceMap.getString("lblEmail.text")); // NOI18N
        lblEmail.setName("lblEmail"); // NOI18N

        txtEmail.setName("txtEmail"); // NOI18N

        lblPhone.setText(resourceMap.getString("lblPhone.text")); // NOI18N
        lblPhone.setName("lblPhone"); // NOI18N

        txtPhoneLeftParenthesis.setText(resourceMap.getString("txtPhoneLeftParenthesis.text")); // NOI18N
        txtPhoneLeftParenthesis.setName("txtPhoneLeftParenthesis"); // NOI18N

        txtPhoneArea.setName("txtPhoneArea"); // NOI18N

        lblPhoneRightParenthesis.setText(resourceMap.getString("lblPhoneRightParenthesis.text")); // NOI18N
        lblPhoneRightParenthesis.setName("lblPhoneRightParenthesis"); // NOI18N

        txtPhoneFirst.setMaximumSize(new java.awt.Dimension(3, 3));
        txtPhoneFirst.setName("txtPhoneFirst"); // NOI18N

        txtPhoneDash.setText(resourceMap.getString("txtPhoneDash.text")); // NOI18N
        txtPhoneDash.setName("txtPhoneDash"); // NOI18N

        txtPhoneLast.setName("txtPhoneLast"); // NOI18N

        lblPhoneExt.setText(resourceMap.getString("lblPhoneExt.text")); // NOI18N
        lblPhoneExt.setName("lblPhoneExt"); // NOI18N

        txtPhoneExt.setName("txtPhoneExt"); // NOI18N

        lblPosition.setText(resourceMap.getString("lblPosition.text")); // NOI18N
        lblPosition.setName("lblPosition"); // NOI18N

        txtPosition.setName("txtPosition"); // NOI18N

        lblCommMethod.setText(resourceMap.getString("lblCommMethod.text")); // NOI18N
        lblCommMethod.setName("lblCommMethod"); // NOI18N

        cboCommMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Email", "Phone" }));
        cboCommMethod.setName("cboCommMethod"); // NOI18N

        lblNotes.setText(resourceMap.getString("lblNotes.text")); // NOI18N
        lblNotes.setName("lblNotes"); // NOI18N

        scpNotes.setName("scpNotes"); // NOI18N

        txaNotes.setColumns(20);
        txaNotes.setRows(5);
        txaNotes.setName("txaNotes"); // NOI18N
        scpNotes.setViewportView(txaNotes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompanyTitle)
                    .addComponent(lblContactTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCity)
                            .addComponent(lblState)
                            .addComponent(lblPhone)
                            .addComponent(lblStreet)
                            .addComponent(lblZip)
                            .addComponent(lblEmail)
                            .addComponent(lblFName))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboState, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPhoneLeftParenthesis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneArea, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPhoneRightParenthesis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneDash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneLast, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPhoneExt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneExt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblCompany)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblIndustryDivision)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboIndustry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPosition)
                            .addComponent(lblCommMethod)
                            .addComponent(lblNotes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                            .addComponent(cboCommMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompanyTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompany)
                    .addComponent(cboCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIndustryDivision)
                    .addComponent(cboIndustry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContactTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName)
                    .addComponent(lblLName)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZip)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(cboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneLeftParenthesis)
                    .addComponent(lblPhoneRightParenthesis)
                    .addComponent(lblPhone)
                    .addComponent(txtPhoneArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneDash)
                    .addComponent(txtPhoneLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneExt)
                    .addComponent(txtPhoneExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPosition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommMethod)
                    .addComponent(cboCommMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotes)
                    .addComponent(scpNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCompanyActionPerformed
        String company = cboCompany.getSelectedItem().toString();

        if (company.equalsIgnoreCase("Cal Poly Pomona") ) {
            lblIndustryDivision.setText("Division:");
        } else {
            lblIndustryDivision.setText("Industry:");
        }
}//GEN-LAST:event_cboCompanyActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed

    }//GEN-LAST:event_txtZipActionPerformed

    private void txtZipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtZipMouseExited

    }//GEN-LAST:event_txtZipMouseExited

    private void txtZipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZipFocusLost
        String city = "";
        String state = "";
        String zipfield = txtZip.getText();
        Database db = new Database("Zip");
        db.and("ZIP", zipfield);
        try {
            ResultSet rs = db.select();
            while (rs.next()) {
                city = rs.getString("CITY");
                state = rs.getString("STATE");
            }
        } catch (Exception e) {
            System.out.println("Could not execute query");
            System.out.println(e.getMessage());
        }
        txtCity.setText(city);
        cboState.setSelectedItem(state);
    }//GEN-LAST:event_txtZipFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCommMethod;
    private javax.swing.JComboBox cboCompany;
    private javax.swing.JComboBox cboIndustry;
    private javax.swing.JComboBox cboState;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommMethod;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblCompanyTitle;
    private javax.swing.JLabel lblContactTitle;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblIndustryDivision;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneExt;
    private javax.swing.JLabel lblPhoneRightParenthesis;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblZip;
    private javax.swing.JScrollPane scpNotes;
    private javax.swing.JTextArea txaNotes;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPhoneArea;
    private javax.swing.JLabel txtPhoneDash;
    private javax.swing.JTextField txtPhoneExt;
    private javax.swing.JTextField txtPhoneFirst;
    private javax.swing.JTextField txtPhoneLast;
    private javax.swing.JLabel txtPhoneLeftParenthesis;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables

    public void clickNew() {
    }
    public void save() {
        Contact record = new Contact();
        // Saves the Industry if it's a new entry
        if (cboIndustry.getSelectedIndex() == -1) {
            Industry indust = new Industry(cboIndustry.getSelectedItem().toString());
            record.setIndustryId(indust.save());
        } else {
            record.setIndustryId(((ComboItem) cboIndustry.getSelectedItem()).id);
        }
        // Saves the Company if it's a new entry
        if (cboCompany.getSelectedIndex() == -1) {
            Company comp = new Company(cboCompany.getSelectedItem().toString());
            record.setCompanyId(comp.save());
        } else {
            record.setCompanyId(((ComboItem) cboCompany.getSelectedItem()).id);
        }
        record.setFname(txtFName.getText());
        record.setLname(txtLName.getText());
        record.setStreet(txtStreet.getText());
        record.setZip(Integer.parseInt(txtZip.getText()));
        record.setCity(txtCity.getText());
        record.setState(cboState.getSelectedItem().toString());
        record.setEmail(txtEmail.getText());
        record.setPhone(Integer.parseInt(txtPhoneArea.getText()), Integer.parseInt(txtPhoneFirst.getText()), Integer.parseInt(txtPhoneLast.getText()), Integer.parseInt(txtPhoneExt.getText()));
        record.setPosition(txtPosition.getText());
        record.setComm_method(cboCommMethod.getSelectedIndex());
        record.setDescription(txaNotes.getText());
        record.save();
    }
    public void clickLoad() {
    }
    public void clickDelete() {
    }
    public void reset() {
        cboCompany.setSelectedIndex(0);
        cboIndustry.setSelectedIndex(0);
        txtFName.setText("");
        txtLName.setText("");
        txtStreet.setText("");
        txtZip.setText("");
        txtCity.setText("");
        cboState.setSelectedIndex(0);
        txtEmail.setText("");
        txtPhoneArea.setText("");
        txtPhoneFirst.setText("");
        txtPhoneLast.setText("");
        txtPhoneExt.setText("");
        txtPosition.setText("");
        cboCommMethod.setSelectedIndex(0);
        txaNotes.setText("");
    }
    public void clickCancel() {
    }
    public void clickEditing() {
    }
    public void clickBrowsing() {
    }
    public void switchTo(String actionCommand) {
        cboCompany.setModel(new ComboBoxModel("company", "name"));
        cboIndustry.setModel(new ComboBoxModel("industry", "industry_name"));
    }
    public void switchAway() {
    }
}