package cis406.correspondence;

import cis406.TableModel;
import cis406.contact.Contact;
import cis406.contact.Contact;
import cis406.correspondence.Correspondence;
import javax.swing.JOptionPane;

/**
 *
 * @author Mark Lenser
 */
public class BrowsePanel extends javax.swing.JPanel {

    /** Creates new form CorrespondenceBrowsePanel */
    public BrowsePanel() {
        initComponents();
        //loadTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCorrespondenceReport = new javax.swing.JTable();

        setName("frmCorrBrowse"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblCorrespondenceReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCorrespondenceReport.setName("tblCorrespondenceReport"); // NOI18N
        jScrollPane1.setViewportView(tblCorrespondenceReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCorrespondenceReport;
    // End of variables declaration//GEN-END:variables

    public void loadTable() {
        tblCorrespondenceReport.setModel(Correspondence.generateTable());
    }
    public void delete() {
        int rowId = getSelectedRow();
        if (Contact.delete(rowId)) {
            JOptionPane.showMessageDialog(null, "Correspondence #" + rowId + " was deleted");
            loadTable();
        } else {
            JOptionPane.showMessageDialog(null, "Correspondence #" + rowId + " could not be found");
        }
    }
    /**
     * Returns 0 if no SQL row found
     * @return
     */
    public int getSelectedRow() {
        int row = tblCorrespondenceReport.getSelectedRow();
        if (row != -1) {
            return ((TableModel) tblCorrespondenceReport.getModel()).getRowId(row);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row first");
            return 0;
        }
    }
}
