package cis406.correspondence;
import cis406.PanelInterface;
import java.awt.CardLayout;

/**
 *
 * @author Mark Lenser
 */
public class CorrespondencePanel extends javax.swing.JPanel implements PanelInterface {
    String activeCard = "Browse";

    /** Creates new form ContactPanel */
    public CorrespondencePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correspondenceEditPanel1 = new cis406.correspondence.EditPanel();
        correspondenceBrowsePanel1 = new cis406.correspondence.BrowsePanel();

        setName("frmCorr"); // NOI18N
        setLayout(new java.awt.CardLayout());

        correspondenceEditPanel1.setName("correspondenceEditPanel1"); // NOI18N
        add(correspondenceEditPanel1, "Edit");

        correspondenceBrowsePanel1.setName("correspondenceBrowsePanel1"); // NOI18N
        correspondenceBrowsePanel1.setVerifyInputWhenFocusTarget(false);
        add(correspondenceBrowsePanel1, "Browse");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cis406.correspondence.BrowsePanel correspondenceBrowsePanel1;
    private cis406.correspondence.EditPanel correspondenceEditPanel1;
    // End of variables declaration//GEN-END:variables


    public void clickReset() {
        if (activeCard.equals("Edit")) {
            correspondenceEditPanel1.reset();
        } else {
            correspondenceBrowsePanel1.loadTable();
        }
    }
    public void clickDelete() {
        if (activeCard.equals("Browse")) {
            correspondenceBrowsePanel1.delete();
        } else {
        }
    }
    public void clickCancel() {
        browsing();
    }
    public void clickLoad() {
        if (activeCard.equals("Browse")) {
            int record = correspondenceBrowsePanel1.getSelectedRow();
            if (record != 0) {
                editing();
                correspondenceEditPanel1.load(record);
            }
        }
    }
    public void clickNew() {
        correspondenceEditPanel1.newCorrespondence();
        editing();
    }
    public void clickSave() {
        if (activeCard.equals("Edit") && correspondenceEditPanel1.save()) {
            browsing();
        }
    }
    public void editing() {
        CardLayout cl = (CardLayout) (getLayout());
        cl.show(this, "Edit");
        activeCard = "Edit";
    }
    public void browsing() {
        CardLayout cl = (CardLayout) (getLayout());
        cl.show(this, "Browse");
        activeCard = "Browse";
        correspondenceBrowsePanel1.loadTable();
    }
    public void switchTo() {
        browsing();
    }
    public Boolean switchAway() {
        return true;
    }
}
